parameters:
- name: subscription
  displayName: scope of testing
  type: string
  default: regression
  values:
  - regression
  - ui
  - api

'''schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
'''

trigger:
- master

pool:
   vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'

- script: |
- task: CmdLine@2
  inputs:
    script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    ${{ if contains(parameters.subscription, 'regression') }}:
      script: |
        python -m pytest -v -s --junitxml=result.xml -o junit_family="xunit1"
    ${{ if contains(parameters.subscription, 'ui') }}:
      script: |
        python -m pytest -v -s -k "ui" --junitxml=result.xml -o junit_family="xunit1"
    ${{ if contains(parameters.subscription, 'api') }}:
      script: |
        python -m pytest -v -s -k "api" --junitxml=result.xml -o junit_family="xunit1"
  displayName: 'pytest'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'result.xml'